spring:
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.113.195.38:3306/user_center
    username: crx
    password: crx257621@
  #设置session失效时间为1天
  session:
    timeout: 86400




